From alpine:latest
WORKDIR /app/
RUN ls /app/
RUN apk add --no-cache bash && mkdir tmp && echo yxh > tmp/a.txt && cat tmp/a.txt
USER daemon
CMD ["sh", "-c", "echo EXEC-CMD1 && whoami"]
# 覆盖CMD1
CMD ["sh", "-c", "echo EXEC-CMD2 && whoami"]
# ENTRYPOINT + CMD 组合
ENTRYPOINT ["sh", "-c", "echo ENTRYPOINT: && whoami && pwd"]
# ENTRYPOINT + CMD 组合
ENTRYPOINT ["echo"]

##################################
## $ docker run --rm -it cmd
## sh -c echo EXEC-CMD2 && whoami
