#docker build  --platform linux/amd64 -f  Dockerfile.deno -t deno .
FROM --platform=linux/amd64 node:18-buster-slim

LABEL maintainer="yxh <yexuehui@momenta.ai>"
WORKDIR /app
RUN  apt update && apt install curl unzip -y && curl -fsSL https://deno.land/install.sh | sh
ENV DENO_INSTALL="/root/.deno"
ENV PATH="$DENO_INSTALL/bin:$PATH"
CMD deno
