#!/usr/bin/env zsh
set -ex
repos=(
js-lib
py-lib
go-lib
c-lib
c-lib/unix/unpv13
a
)

opwd=`pwd`
cd $HOME/www
for repo in "${repos[@]}"; do
    echo $repo
    cd $HOME/www/$repo
    git pull origin master
    git push origin HEAD
done
cd $opwd
